support anthropicBaseURL , openaiAPIKey, anthropicAPIKey cli params
mark3labs/mcphost pull request #6
Opened 2024-12-21 09:58 UTC by GargantuaX

2024-12-25 14:24 UTC, ezynda3 commented
First off, thanks so much for the PR! It looks good. One small thing though, could you remove the non-English comments in the code or translate them to English? After that, I will merge this.

Cheers!

2024-12-25 14:41 UTC, ezynda3 commented on cmd/root.go
> +	anthropicBaseURL string // 新增 anthropicBaseURL 变量
Can we remove these comments?

2024-12-25 14:42 UTC, ezynda3 requested changes

2024-12-25 14:42 UTC, ezynda3 commented on cmd/root.go
> +	// Fix: 修改格式，确保每个标志都正确注册
Can we remove this comment?

2024-12-27 08:17 UTC, GargantuaX commented
Done

2024-12-27 11:10 UTC, merged